### ISSUE TITLE
CDK v3.0 Roadmap

### ISSUE THREAD

**Issue by johnmay** [cdk/cdk#823]
Check lists of nice to haves for CDK 3.0 some of these are large sweeping API changes hence v3.0.

- [ ] Switch IElement.H etc to int rather than byte (pre-v3.0 possible)
- [ ] Use primitive types in IAtom, i.e. atomic number and mass=0 rather than null (pre-v3.0 maybe)
- [ ] first-class Sgroup support (need interfaces) (pre-v3.0 possible)
- [ ] Move classes to different packages for #626, may not be possible overall but some should be (v3.0 only - will be painful upgrade downstream but good long run, less annoying than IMolecule -> IAtomContainer)
- [ ] Remove old AtomContainer implementation (see plan in https://github.com/cdk/cdk/wiki/AtomContainer2) (v3.0 only)
- [ ] Move to Java 11 for JENA dependency (v3.0 only)

**Comment by uli-f** [comment]
I'd appreciate it if support for the Stream API will be added to containers such as IAtomContainerSet:

public Stream<IAtomContainer> stream() { ... }

I use the Stream API a lot and the CDK feels a bit dated here.

**Comment by johnmay** [comment]
Thanks for the feedback, this would be quite simple. Ironically I never liked those APIs as I think it should just return a normal ``Set<IAtomContainer>`` or ``List<IAtomContainer>``

**Comment by uli-f** [comment]
That might be even better 👍🏼 

It sometimes feels a bit odd to navigate the CDK objects as there are customized solutions that are not adhering to standards (such as the IAtomContainerSet).

**Comment by egonw** [comment]
IIRC, the reason for `IAtomContainerSet` over `List<IAtomContainer` is that it could still have the same API as `IChemObject`. This was/is important for certain use cases, like JChemPaint with the listener stack. In fact, before we wrote the interfaces, the listeners was a hard requirement, so we did not have much choice.

**Comment by egonw** [comment]
Remember, and Tim Dudgeon looked it up, the CDK was written in the time of Java 1.3!

**Comment by uli-f** [comment]
I fully understand, my comment wasn't meant as criticism 😃 
In my experience, if the cheminformatics toolkit also serves as a backend for a chemical sketcher it sometimes looks a bit odd from the API side when only working with the cheminformatics functionality.

**Comment by johnmay** [comment]
Something you might find useful Uli is we can store reactions as molecules. See [ReactionManipulator](http://cdk.github.io/cdk/latest/docs/api/index.html?org/openscience/cdk/tools/manipulator/ReactionManipulator.html).toMolecule(); and toReaction();

**Comment by mjw99** [comment]
Hi John, I could probably help with the JUnit 5 bit; I've done a few JUnit 4 to 5 migrations recently.

**Comment by johnmay** [comment]
No worries, I was going to use sed as I think most of it is find/replace the package names :-)

**Comment by uli-f** [comment]
- [ ] bump Java language level to 17 (as discussed with @johnmay in #892)

**Comment by uli-f** [comment]
@johnmay I would like to pick something from the list.

Would you consider any of the following issues suitable:

- Use primitive types in IAtom, i.e. atomic number and mass=0 rather than null (pre-v3.0 maybe)
- Stream API on AtomContainer Set etc, Casey should it’s self be iterable
- Java 17

**Comment by egonw** [comment]
> * Use primitive types in IAtom, i.e. atomic number and mass=0 rather than null (pre-v3.0 maybe)

While "null" is not ideal, using 0 is worse, imho.

**Comment by johnmay** [comment]
@uli-f Thanks for the offer to help. Some of these we need to "start" a v3.0 branch for which we're not quite at yet. However the Stream API for ACSet would be good. Although I think I misstype. Basically IMHO these (there are multiple of them) should at minimum implement ``Iterable<IAtomContainer>`` so you can do this:

```
for (IAtomContainer mol : reaction.getAgents()) {

}
```

Directly implementing the Stream API might also give you this plus extra?

@egonw NULL is just a different 0 :-). But yes I get you wanted to separate unset/undefined from 0. It's on the list because I get fed up with typing:

```
Integer hcnt = atom.getImplicitHydrogenCount();
if (hcnt == null)
  hcnt = 0;
// etc for atomic number etc
```

Everywhere, although hydrogen count is perhaps the one place it is most useful to be unset. My view was it's more convenient to handle these when you need to i.e. via a flag and then the common case of everything being set is much more convenient and efficient.

```
if (atom.getFlag(IAtom.UndefinedHydrogenCount)) {
   // do the "special case"
}
```

That's a big change though, hence v3.0.

BTW SonarCloud really didn't like CDKConstant.UNSET for null as it couldn't inspect the type, I went through and ignored the warnings recently but probably should just use null.

```java
Integer atomicNumber = (Integer)CDKConstant.UNSET; // it sees as (Integer)(Object){null}; 
```

**Comment by johnmay** [comment]
Perhaps: 

```
if (atom.isDefined(IAtom.HydrogenCount)) {
   // do the "special case"
}
```

**Comment by egonw** [comment]
> @egonw NULL is just a different 0 :-). But yes I get you wanted to separate unset/undefined from 0. 

This distinction showed quite essential in the early CDK days. A lot of input we get is not fully defined and for a computer to understand the difference between 0 and unset/undefined, this needs to be explicit. A lot of bugs could only be fixed by making this distinction. The extra work that results from that experience is good: it is dealing with the difference. The alternative is to always assume it is set, and that just causes a lot of trouble.

**Comment by johnmay** [comment]
I think this was perhaps based on the restricted documentation from MDL/Daylight. i.e. Coming from SDF/SMILES everything is set by design. I guess CML you have missing fields though?

Anyways I've reorganised the list to make it clear what I think needs a v3.0 branch but I don't want to fork yet (maintenance burden).

@uli-f The Stereo Map in atomcontainer is another (potentially simple one) where the stereochemistry should/could be indexed by the "focus" atom/bond. It's currently just a list, I hit this recently with the SMIRKS in that add new stereo I want to remove the old. Currently it's a pain but a Map would handle this automatically.

```
IAtomContainer mol;

IStereoElement<IAtom,?> atom.getStereo();
IStereoElement<IAtom,?> bond.getStereo();

// implemented via:

IStereoElement<IAtom,?> getStereo(atom);
IStereoElement<IBond,?> getStereo(bond);

// which could perhaps also be public but I think package-private will be fine.
```

Implement as

```
AtomContainer.java:
Map<IChemObject,IStereoElement<?,?> map;
```

The only pain is have 5 implementations to update.

**Comment by uli-f** [comment]
Thanks @johnmay for the suggestion re the `Stereo Map`. I am happy to take a closer look at and assess both `Stereo Maps` and `AtomContainer` etc `Iterables/Stream API`.

Will report back in a few and let you know prior to starting any work on it.

In general: if there are any tasks well suited for me to make myself more familiar with CDK I am happy to take these on.

**Comment by uli-f** [comment]
Oh, and this might be another breaking change for 3.0:

- [ ] change `AtomContainerManipulator::percieveAtomTypesAndConfigureAtoms` to `AtomContainerManipulator::perceiveAtomTypesAndConfigureAtoms` 😃

**Comment by johnmay** [comment]
> * AtomContainerManipulator::perceiveAtomTypesAndConfigureAtoms

Indeed, I always thought that was too long a name but I can't think of a better one :-)

**Comment by javadev** [comment]
We have the option to proceed with releasing version 2.10, ensuring compatibility with Java 8. This approach would enable us to meet any existing requirements for Java 8 while advancing to the latest version of our application.

**Comment by johnmay** [comment]
Yes I should do a 2.10 release
